#!/usr/bin/env python
"""
BorderCloak

Copyright (c) 2013 Micah Lee <micah@micahflee.com>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
"""

import pygtk
pygtk.require('2.0')
import gtk

version = '0.1development'

class Menu(object):
    def __init__(self, window, container=None):
        self.window = window
        if container: self.window.remove(container)

        self.box = gtk.VBox(False, 10)
        self.window.add(self.box)
        self.box.show()

        self.label1 = gtk.Label('Traveling? Excellent! Choose one:')
        self.box.pack_start(self.label1, True, True, 0)
        self.label1.show()

        self.package_button = gtk.Button("Compress, Encrypt, Upload")
        self.package_button.connect("clicked", self.package, None)
        self.box.add(self.package_button)
        self.package_button.show()

        self.unpackage_button = gtk.Button("Download, Decrypt, Extract")
        self.unpackage_button.connect("clicked", self.unpackage, None)
        self.box.add(self.unpackage_button)
        self.unpackage_button.show()

    def package(self, widget, data=None):
        Package(self.window, self.box)
    
    def unpackage(self, widget, data=None):
        Unpackage(self.window, self.box)

class Package(object):
    def __init__(self, window, container=None):
        self.window = window
        if container: self.window.remove(container)

        self.box = gtk.VBox(False, 10)
        self.window.add(self.box)
        self.box.show()

        # step 1
        self.label1 = gtk.Label('Step 1: Choose the folders you would like to have access to')
        self.box.pack_start(self.label1, True, True, 0)
        self.label1.show()

        self.step1_box = gtk.HBox(False, 10)
        self.box.pack_start(self.step1_box, True, True, 0)
        self.step1_box.show()

        # todo: make a list of folders that have been selected
        self.folder_list = gtk.Label('this is a placeholder\na list of folders\nthat get selected')
        self.step1_box.pack_start(self.folder_list, True, True, 0)
        self.folder_list.show()

        self.step1_buttons_box = gtk.VBox(False, 10)
        self.step1_box.pack_start(self.step1_buttons_box, True, True, 0)
        self.step1_buttons_box.show()

        # todo: make folder_chooser only let you choose folders, not files
        self.folder_chooser = gtk.FileChooserButton('Select a folder')
        self.step1_buttons_box.pack_start(self.folder_chooser, True, True, 0)
        self.folder_chooser.show()

        self.delete_folder_button = gtk.Button('Delete')
        self.step1_buttons_box.pack_start(self.delete_folder_button, True, True, 0)
        self.delete_folder_button.show()

        # step 2
        self.label2 = gtk.Label('Step 2: Choose an encryption passphrase (memorize it!)')
        self.box.pack_start(self.label2, True, True, 0)
        self.label2.show()

        self.passphrase = gtk.Entry()
        self.passphrase.set_visibility(False)
        self.box.pack_start(self.passphrase, True, True, 0)
        self.passphrase.show()

        # step 3
        self.label3 = gtk.Label('Step 3: SSH credentials')
        self.box.pack_start(self.label3, True, True, 0)
        self.label3.show()

        self.ssh_host_box = gtk.HBox(False, 10)
        self.box.pack_start(self.ssh_host_box, True, True, 0)
        self.ssh_host_box.show()
        self.ssh_host_label = gtk.Label("Host")
        self.ssh_host_box.pack_start(self.ssh_host_label, True, True, 0)
        self.ssh_host_label.show()
        self.ssh_host_entry = gtk.Entry()
        self.ssh_host_box.pack_start(self.ssh_host_entry, True, True, 0)
        self.ssh_host_entry.show()

        self.ssh_username_box = gtk.HBox(False, 10)
        self.box.pack_start(self.ssh_username_box, True, True, 0)
        self.ssh_username_box.show()
        self.ssh_username_label = gtk.Label("Username")
        self.ssh_username_box.pack_start(self.ssh_username_label, True, True, 0)
        self.ssh_username_label.show()
        self.ssh_username_entry = gtk.Entry()
        self.ssh_username_box.pack_start(self.ssh_username_entry, True, True, 0)
        self.ssh_username_entry.show()

        self.ssh_password_box = gtk.HBox(False, 10)
        self.box.pack_start(self.ssh_password_box, True, True, 0)
        self.ssh_password_box.show()
        self.ssh_password_label = gtk.Label("Password")
        self.ssh_password_box.pack_start(self.ssh_password_label, True, True, 0)
        self.ssh_password_label.show()
        self.ssh_password_entry = gtk.Entry()
        self.ssh_password_entry.set_visibility(False)
        self.ssh_password_box.pack_start(self.ssh_password_entry, True, True, 0)
        self.ssh_password_entry.show()

        self.ssh_location_box = gtk.HBox(False, 10)
        self.box.pack_start(self.ssh_location_box, True, True, 0)
        self.ssh_location_box.show()
        self.ssh_location_label = gtk.Label("Location")
        self.ssh_location_box.pack_start(self.ssh_location_label, True, True, 0)
        self.ssh_location_label.show()
        self.ssh_location_entry = gtk.Entry()
        self.ssh_location_entry.set_text('~/bordercloak.crypt')
        self.ssh_location_box.pack_start(self.ssh_location_entry, True, True, 0)
        self.ssh_location_entry.show()




class Unpackage(object):
    def __init__(self, window, container=None):
        self.window = window
        if container: self.window.remove(container)
        
        print 'Download, Decrypt, Extract'

class BorderCloak(object):
    def __init__(self):
        # open a window
        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.set_title("BorderCloak")
        self.window.set_position(gtk.WIN_POS_CENTER)
        self.window.set_border_width(10)
        self.window.connect("delete_event", self.delete_event)
        self.window.connect("destroy", self.destroy)

        Menu(self.window)
       
        # show the window
        self.window.show()
        gtk.main()

    # exit
    def delete_event(self, widget, event, data=None):
        return False
    def destroy(self, widget, data=None):
        gtk.main_quit()


if __name__ == "__main__":
    print 'BorderCloak {0}'.format(version)
    print 'By Micah Lee, licensed under GPLv3'

    app = BorderCloak()
