#!/usr/bin/env python
"""
BorderCloak

Copyright (c) 2013 Micah Lee <micah@micahflee.com>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
"""

import pygtk
pygtk.require('2.0')
import gtk

version = '0.1development'

class BorderCloak(object):
    def __init__(self):
        # open a window
        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.set_title("BorderCloak")
        self.window.set_position(gtk.WIN_POS_CENTER)
        self.window.set_border_width(10)
        self.window.connect("delete_event", self.delete_event)
        self.window.connect("destroy", self.destroy)
        
        # vertical box
        self.box = gtk.VBox(False, 10)
        self.window.add(self.box)
        self.box.show()

        # label
        self.label1 = gtk.Label('Traveling? Excellent! Choose one:')
        self.box.pack_start(self.label1, True, True, 0)
        self.label1.show()

        # buttons
        self.package_button = gtk.Button("Compress, Encrypt, and Upload")
        self.package_button.connect("clicked", self.package, None)
        self.box.add(self.package_button)
        self.package_button.show()

        self.unpackage_button = gtk.Button("Download, Decrypt, Extract")
        self.unpackage_button.connect("clicked", self.unpackage, None)
        self.box.add(self.unpackage_button)
        self.unpackage_button.show()
        
        # show the window
        self.window.show()
        gtk.main()

    def package(self, widget, data=None):
        print 'package clicked'
    
    def unpackage(self, widget, data=None):
        print 'unpackage clicked'

    # exit
    def delete_event(self, widget, event, data=None):
        return False
    def destroy(self, widget, data=None):
        gtk.main_quit()


if __name__ == "__main__":
    print 'BorderCloak {0}'.format(version)
    print 'By Micah Lee, licensed under GPLv3'

    app = BorderCloak()
